---
services:
  db:
    image: postgres
    container_name: tunneling-db
    restart: unless-stopped
    ports: ['${POSTGRES_PORT}:5432']
    volumes:
      - ./db/sql/create.sql:/docker-entrypoint-initdb.d/01_create.sql
      - ./db/PG_data/postgres-data:/var/lib/postgresql/data
    env_file: [.env]
  api:
    build: ./backend
    container_name: tunneling-api
    restart: unless-stopped
    ports: ['${BACKEND_PORT_SSL}:443', '${BACKEND_PORT}:80']
    depends_on: [db]
    env_file: [.env]
