CREATE TABLE "t_users" (
  "user_id" int PRIMARY KEY,
  "firstname" varchar(30) NOT NULL,
  "lastname" varchar(30) NOT NULL,
  "password" varchar(50) NOT NULL,
  "isAdmin" bool NOT NULL DEFAULT false,
  "failedAttempts" int NOT NULL DEFAULT 0
);

CREATE TABLE "t_games" (
  "game_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "point" bool NOT NULL,
  "created_at" datetime NOT NULL DEFAULT (now())
);

CREATE TABLE "t_logins" (
  "login_id" int PRIMARY KEY,
  "user_id" int NOT NULL,
  "time" datetime NOT NULL,
  "state" bool NOT NULL
);

ALTER TABLE "t_logins" ADD FOREIGN KEY ("user_id") REFERENCES "t_users" ("user_id");

ALTER TABLE "t_games" ADD FOREIGN KEY ("user_id") REFERENCES "t_users" ("user_id");
