CREATE TABLE "t_users" (
    "user_id" int PRIMARY KEY,
    "firstname" varchar(30) NOT NULL,
    "lastname" varchar(30) NOT NULL,
    "password" varchar(50) NOT NULL,
    "is_admin" bool NOT NULL DEFAULT FALSE,
    "failed_attempts" int NOT NULL DEFAULT 0
);

CREATE TABLE "t_games" (
    "game_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" int NOT NULL,
    "point" bool NOT NULL,
    "created_at" timestamp NOT NULL DEFAULT (now()),
    "counts" bool NOT NULL DEFAULT TRUE
);

CREATE TABLE "t_logins" (
    "login_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" int NOT NULL,
    "time" timestamp NOT NULL DEFAULT (now()),
    "state" bool NOT NULL
);

ALTER TABLE "t_logins"
    ADD FOREIGN KEY ("user_id") REFERENCES "t_users" ("user_id");

ALTER TABLE "t_games"
    ADD FOREIGN KEY ("user_id") REFERENCES "t_users" ("user_id");

